// =====================================================================
//  main.bicep  (subscription scope)
//  Entry point for `azd up`. Creates the resource group and deploys
//  all platform resources into it.
// =====================================================================
targetScope = 'subscription'

metadata description = 'data-driven - one-command Azure deployment.'

@minLength(1)
@maxLength(64)
@description('Name of the azd environment (drives resource naming).')
param environmentName string

@minLength(1)
@description('Primary region for the app tier: Container Apps, Cosmos, ACR, Key Vault, monitoring.')
param location string = 'northeurope'

@description('Region for AI Foundry + all AI/model deployments. Sweden Central is required for feature availability.')
param aiLocation string = 'swedencentral'

@description('Deploy Azure Communication Services email (one-click outreach).')
param deployEmail bool = false

@description('Allow signing in with an emailed code. Needs a custom mail domain - a managed domain only permits 10 sends an hour per subscription.')
param enableOtpLogin bool = false

@description('Enable admin backup, initialization and staged data replacement.')
param enableDataRecovery bool = true

@description('Independent environment recovery credential, generated once by preprovision.')
@secure()
@minLength(32)
param dataRecoveryKey string

@description('Enable the authenticated external copilot API and A2A interface.')
param enableCopilotIntegrations bool = false

@description('Enable the Telegram adapter. Requires external copilot and pre-existing Key Vault secrets.')
param enableTelegram bool = false

@description('Key Vault secret URI holding the integration client configuration JSON.')
param copilotClientsKeyVaultUrl string = ''

@description('Allowed Entra tenant for external access tokens. Empty disables Entra authentication.')
param copilotEntraTenantId string = ''

@description('Expected audience of Entra access tokens for this API.')
param copilotEntraAudience string = ''

@description('Required Entra delegated scope or application role.')
param copilotEntraRole string = 'Copilot.Invoke'

@description('Key Vault secret URI holding the Telegram bot token.')
param telegramBotTokenKeyVaultUrl string = ''

@description('Key Vault secret URI holding a random Telegram webhook secret of at least 32 characters.')
@secure()
param telegramWebhookSecretKeyVaultUrl string = ''

@description('Telegram bot username without the at-sign.')
param telegramBotUsername string = ''

@description('Email address for the monthly cost-budget alert on the resource group. Empty disables it.')
param budgetContactEmail string = ''

@description('Auth.js session secret. Generated by the azd preprovision hook when absent.')
@secure()
@minLength(32)
param authSecret string

@description('Object id of the deploying user/service principal (azd sets AZURE_PRINCIPAL_ID).')
param principalId string = ''

@description('Chat model to deploy in Azure AI Foundry.')
param chatModelName string = 'gpt-5.4-mini'

@description('Chat model version available in the selected AI region.')
param chatModelVersion string = '2026-03-17'

@description('Chat deployment capacity. Confirm model quota before deploying a new subscription.')
@minValue(1)
param chatModelCapacity int = 324

@description('Embedding deployment capacity.')
@minValue(1)
param embeddingModelCapacity int = 50

@description('Previously deployed image, maintained by the deployment runner and azd.')
param webImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Monthly resource-group budget, enabled by budgetContactEmail.')
@minValue(1)
param budgetAmount int = 100

@description('Daily Log Analytics ingestion cap in GB.')
@minValue(1)
param logAnalyticsDailyQuotaGb int = 1

@description('reasoning_effort for "Think deeply". Ordinary asks always send "low".')
@allowed([
  'low'
  'medium'
  'high'
  'xhigh'
  'max'
])
param reasoningEffort string = 'high'

@description('Name of the Foundry prompt agent created at deploy time.')
param agentName string = 'data-driven-copilot'

var resourceToken = toLower(uniqueString(subscription().id, environmentName, location))
var tags = {
  'azd-env-name': environmentName
  application: 'data-driven'
}

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: 'rg-${environmentName}'
  location: location
  tags: tags
}

module resources 'resources.bicep' = {
  name: 'resources'
  scope: rg
  params: {
    location: location
    aiLocation: aiLocation
    resourceToken: resourceToken
    tags: tags
    deployEmail: deployEmail
    enableOtpLogin: enableOtpLogin
    enableDataRecovery: enableDataRecovery
    dataRecoveryKey: dataRecoveryKey
    enableCopilotIntegrations: enableCopilotIntegrations
    enableTelegram: enableTelegram
    copilotClientsKeyVaultUrl: copilotClientsKeyVaultUrl
    copilotEntraTenantId: copilotEntraTenantId
    copilotEntraAudience: copilotEntraAudience
    copilotEntraRole: copilotEntraRole
    telegramBotTokenKeyVaultUrl: telegramBotTokenKeyVaultUrl
    telegramWebhookSecretKeyVaultUrl: telegramWebhookSecretKeyVaultUrl
    telegramBotUsername: telegramBotUsername
    chatModelName: chatModelName
    chatModelVersion: chatModelVersion
    chatModelCapacity: chatModelCapacity
    embeddingModelCapacity: embeddingModelCapacity
    webImage: webImage
    reasoningEffort: reasoningEffort
    agentName: agentName
    authSecret: authSecret
    deployerPrincipalId: principalId
    budgetContactEmail: budgetContactEmail
    budgetAmount: budgetAmount
    logAnalyticsDailyQuotaGb: logAnalyticsDailyQuotaGb
  }
}

// azd-consumed outputs
output AZURE_LOCATION string = location
output AZURE_RESOURCE_GROUP string = rg.name
output AZURE_CONTAINER_REGISTRY_ENDPOINT string = resources.outputs.AZURE_CONTAINER_REGISTRY_ENDPOINT
output AZURE_CONTAINER_REGISTRY_NAME string = resources.outputs.AZURE_CONTAINER_REGISTRY_NAME
output WEB_URI string = resources.outputs.WEB_URI
output COSMOS_ENDPOINT string = resources.outputs.COSMOS_ENDPOINT
output COSMOS_DATABASE string = resources.outputs.COSMOS_DATABASE
output AZURE_OPENAI_ENDPOINT string = resources.outputs.AZURE_OPENAI_ENDPOINT
output AZURE_OPENAI_DEPLOYMENT string = resources.outputs.AZURE_OPENAI_DEPLOYMENT
output AZURE_AI_FOUNDRY_NAME string = resources.outputs.AZURE_AI_FOUNDRY_NAME
output AZURE_AI_PROJECT_ENDPOINT string = resources.outputs.AZURE_AI_PROJECT_ENDPOINT
output AZURE_AI_PROJECT_NAME string = resources.outputs.AZURE_AI_PROJECT_NAME
output AZURE_AI_AGENT_NAME string = resources.outputs.AZURE_AI_AGENT_NAME
output AGENT_INSTRUCTIONS string = resources.outputs.AGENT_INSTRUCTIONS
output KEY_VAULT_NAME string = resources.outputs.KEY_VAULT_NAME
output MANAGED_IDENTITY_CLIENT_ID string = resources.outputs.MANAGED_IDENTITY_CLIENT_ID
output AZURE_SEARCH_ENDPOINT string = resources.outputs.AZURE_SEARCH_ENDPOINT
output AZURE_SEARCH_NAME string = resources.outputs.AZURE_SEARCH_NAME
output AZURE_SEARCH_CONNECTION_NAME string = resources.outputs.AZURE_SEARCH_CONNECTION_NAME
output AZURE_SEARCH_WEB_KS string = resources.outputs.AZURE_SEARCH_WEB_KS
output AZURE_SEARCH_KNOWLEDGE_BASE string = resources.outputs.AZURE_SEARCH_KNOWLEDGE_BASE
output AZURE_EMBEDDING_DEPLOYMENT string = resources.outputs.AZURE_EMBEDDING_DEPLOYMENT
output APP_INSIGHTS_WORKBOOK_ID string = resources.outputs.APP_INSIGHTS_WORKBOOK_ID
