// =====================================================================
//  Resource module (resource-group scope)
//  Provisions the full platform footprint for data-driven.
// =====================================================================
metadata description = 'Core resources: Container Apps, Cosmos DB, ACR, Key Vault, AI Foundry, monitoring.'

@description('Primary location for the app tier (Container Apps, Cosmos, ACR, Key Vault, monitoring).')
param location string

@description('Region for AI Foundry + model deployments (Sweden Central).')
param aiLocation string = 'swedencentral'

@description('Deterministic token to make resource names unique.')
param resourceToken string

@description('Tags applied to every resource.')
param tags object

@description('Container image for the web app. azd overrides this after the first build.')
param webImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Chat model to deploy in Azure AI Foundry. One model serves both ordinary and deep asks.')
param chatModelName string = 'gpt-5.4-mini'

@description('reasoning_effort sent when the user turns on "Think deeply". Ordinary asks always send "low". Not "minimal" — that disables parallel tool calls, and the copilot is a tool-calling loop.')
@allowed([
  'low'
  'medium'
  'high'
  'xhigh'
  'max'
])
param reasoningEffort string = 'high'

@description('Chat model version.')
param chatModelVersion string = '2026-03-17'

@description('Deployment SKU capacity (thousands of tokens/min) for the chat model.')
param chatModelCapacity int = 30

@description('Foundry project name (new Foundry project, child of the account).')
param aiProjectName string = 'data-driven'

@description('Name of the Foundry prompt agent created at deploy time (visible in the Foundry portal).')
param agentName string = 'data-driven-copilot'

@description('System instructions for the hosted prompt agent. Surfaced as the AGENT_INSTRUCTIONS output, which the postprovision hook uses in preference to its own default — so this is the copy that actually ships.')
param agentInstructions string = 'You are the OOVIE BD Copilot for OOVIE Studios, a studio that builds AI-native music and video experiences for brands. You help the business-development team reason over their client pipeline. Your tools are described in the OpenAPI document you were given - read it and route deliberately; never invent a capability it does not list. Leads are ranked by a two-axis priority model: an Opportunity index (budget, weighted by how confident that number is, plus strategic value) and a Winnability index (stage probability, recency, access, receptivity), combined with a geometric mean so a lead must be decent on BOTH to rank - ease of delivery is reported but never blended in. Rankings cover open deals only. Ground every answer in tool results - never invent leads, numbers, scores, dates or sources; if you do not have the data, say so. Access is granular: 44 permissions, each either on/off or scoped to none/own/team/all, so every tool runs as the signed-in user and may legitimately refuse. If one does, say which permission is missing and who to ask - never try another route to the same data. You may draft outreach but never send it; an admin approves and sends. You cannot delete anything. Be concise, concrete and decision-oriented: lead with the answer, then the evidence and the sources you used.'

@description('Auth.js session secret. Injected as a Container Apps secret; generated by the azd preprovision hook when absent.')
@secure()
@minLength(32)
param authSecret string

@description('Object id of the deploying principal (azd AZURE_PRINCIPAL_ID); granted rights to create the agent.')
param deployerPrincipalId string = ''

@description('Deploy Azure Communication Services email (one-click outreach). Off by default.')
param deployEmail bool = false

@description('Allow signing in with an emailed code. Requires a CUSTOM mail domain: an Azure Managed Domain permits only 10 sends per hour per subscription, which sign-in traffic would exhaust.')
param enableOtpLogin bool = false

@description('Monthly cost budget (in the billing currency) tracked on the resource group. Used only when a budget contact email is set.')
param budgetAmount int = 100

@description('Email address notified on cost-budget thresholds. Empty string disables the budget + alert.')
param budgetContactEmail string = ''

@description('Budget start date (must be the first of a month). Defaults to the current month.')
param budgetStartDate string = utcNow('yyyy-MM-01')

@description('Daily ingestion cap (GB) for the Log Analytics workspace. Protects against runaway telemetry cost; raise if legitimate telemetry is being clipped.')
param logAnalyticsDailyQuotaGb int = 1

// ---- naming ---------------------------------------------------------
var prefix = 'datadriven'
var law = '${prefix}-log-${resourceToken}'
var appiName = '${prefix}-appi-${resourceToken}'
var acrName = replace('${prefix}acr${resourceToken}', '-', '')
var kvName = take(replace('${prefix}kv${resourceToken}', '-', ''), 24)
var uamiName = '${prefix}-id-${resourceToken}'
var cosmosName = '${prefix}-cosmos-${resourceToken}'
var caeName = '${prefix}-cae-${resourceToken}'
var appName = '${prefix}-web-${resourceToken}'
var aiName = '${prefix}-ai-${resourceToken}'
var acsName = '${prefix}-acs-${resourceToken}'
var emailServiceName = '${prefix}-email-${resourceToken}'
var vnetName = '${prefix}-vnet-${resourceToken}'
var cosmosPeName = '${prefix}-pe-cosmos-${resourceToken}'
var searchName = '${prefix}-search-${resourceToken}'
var searchPeName = '${prefix}-pe-search-${resourceToken}'

var cosmosDatabase = 'bd'

// built-in role definition IDs
var roleAcrPull = '7f951dda-4ed3-4680-a7ca-43fe172d538d' // AcrPull
var roleKvSecretsUser = '4633458b-17de-408a-b874-0445c86b69e6' // Key Vault Secrets User
var roleOpenAIUser = '5e0bd9bd-7b93-4f28-af87-19fc36ad61bd' // Cognitive Services OpenAI User (inference)
var roleCogSvcUser = 'a97b65f3-24c7-4388-baec-2e87135dc908' // Cognitive Services User (read account/deployments)
var roleSpeechUser = 'f2dc8367-1007-4938-bd23-fe263f013447' // Cognitive Services Speech User (keyless STT/TTS)
var roleFoundryUser = '53ca6127-db72-4b80-b1b0-d745d6d5456d' // Foundry User (create/edit + consume agents, data plane)
var roleFoundryProjectManager = 'eadc314b-1a2d-4efa-be10-5d325db5065e' // Foundry Project Manager (deployer creates agent)

// Voice (keyless STT/TTS on the AI Services account). Luca = multilingual MAI-Voice-2.
var speechVoice = 'it-IT-Luca:MAI-Voice-2'
var speechLang = 'en-US'

// Foundry IQ (agentic retrieval) — embeddings model + Azure AI Search roles.
var roleSearchIndexReader = '1407120a-92aa-4202-b7e9-c0e197c71c8f' // Search Index Data Reader
var roleSearchServiceContributor = '7ca78c08-252a-4471-8644-bb5ff32d4ba0' // Search Service Contributor (manage indexes / knowledge sources / knowledge bases)
var embedModelName = 'text-embedding-3-large'
var embedModelVersion = '1'
var searchWebKsName = 'web-grounding' // "web" knowledge source (Grounding with Bing)
var searchKbName = 'web-kb' // knowledge base that fronts the web knowledge source
var roleCosmosDataContributor = '00000000-0000-0000-0000-000000000002' // Cosmos DB Built-in Data Contributor
var roleCommunicationEmailOwner = '09976791-48a7-449e-bb21-39d1a415f350' // Communication and Email Service Owner (keyless send)

// =====================================================================
//  Identity
// =====================================================================
resource uami 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: uamiName
  location: location
  tags: tags
}

// =====================================================================
//  Observability
// =====================================================================
resource logs 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: law
  location: location
  tags: tags
  properties: {
    retentionInDays: 30
    sku: { name: 'PerGB2018' }
    // Cost hardening: cap daily ingestion so a telemetry storm cannot run up cost.
    workspaceCapping: {
      dailyQuotaGb: logAnalyticsDailyQuotaGb
    }
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appiName
  location: location
  tags: tags
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logs.id
    DisableLocalAuth: true
  }
}

// Azure Monitor Workbook pinned to the App Insights component: requests,
// failures, latency, dependencies and exceptions at a glance (no need to open
// the portal query editor). serializedData is the workbook JSON as a string.
// Grounded: https://learn.microsoft.com/azure/templates/microsoft.insights/2023-06-01/workbooks
var workbookContent = {
  version: 'Notebook/1.0'
  items: [
    {
      type: 1
      content: {
        json: 'data-driven - application health. Requests, failures, latency, dependencies and exceptions for the web app. Scope: this Application Insights component. Use the time range control to adjust the window.'
      }
    }
    {
      type: 3
      content: {
        version: 'KqlItem/1.0'
        query: 'requests | summarize Requests = count() by bin(timestamp, 30m)'
        size: 0
        title: 'Request volume'
        queryType: 0
        resourceType: 'microsoft.insights/components'
        visualization: 'timechart'
      }
    }
    {
      type: 3
      content: {
        version: 'KqlItem/1.0'
        query: 'requests | where success == false | summarize Failed = count() by bin(timestamp, 30m)'
        size: 0
        title: 'Failed requests'
        queryType: 0
        resourceType: 'microsoft.insights/components'
        visualization: 'timechart'
      }
    }
    {
      type: 3
      content: {
        version: 'KqlItem/1.0'
        query: 'requests | summarize AvgDurationMs = round(avg(duration), 1) by bin(timestamp, 30m)'
        size: 0
        title: 'Average server response time (ms)'
        queryType: 0
        resourceType: 'microsoft.insights/components'
        visualization: 'timechart'
      }
    }
    {
      type: 3
      content: {
        version: 'KqlItem/1.0'
        query: 'requests | summarize Count = count(), AvgMs = round(avg(duration), 1), FailRatePct = round(100.0 * countif(success == false) / count(), 1) by name | top 10 by Count desc'
        size: 0
        title: 'Top operations'
        queryType: 0
        resourceType: 'microsoft.insights/components'
        visualization: 'table'
      }
    }
    {
      type: 3
      content: {
        version: 'KqlItem/1.0'
        query: 'dependencies | where success == false | summarize Failures = count() by target, type | top 15 by Failures desc'
        size: 0
        title: 'Dependency failures (Cosmos, AI, Search)'
        queryType: 0
        resourceType: 'microsoft.insights/components'
        visualization: 'table'
      }
    }
    {
      type: 3
      content: {
        version: 'KqlItem/1.0'
        query: 'exceptions | summarize Count = count() by bin(timestamp, 1h), type'
        size: 0
        title: 'Exceptions over time'
        queryType: 0
        resourceType: 'microsoft.insights/components'
        visualization: 'timechart'
      }
    }
  ]
}

resource workbook 'Microsoft.Insights/workbooks@2023-06-01' = {
  name: guid(appInsights.id, 'app-health')
  location: location
  tags: tags
  kind: 'shared'
  properties: {
    displayName: 'data-driven - application health'
    category: 'workbook'
    serializedData: string(workbookContent)
    sourceId: appInsights.id
    version: 'Notebook/1.0'
  }
}

// Opt-in monthly cost budget on the resource group: alert at 80% forecast and
// 100% actual spend. Skipped entirely unless a contact email is supplied.
// Grounded: https://learn.microsoft.com/azure/templates/microsoft.consumption/2023-11-01/budgets
resource budget 'Microsoft.Consumption/budgets@2023-11-01' = if (!empty(budgetContactEmail)) {
  name: '${prefix}-budget-${resourceToken}'
  properties: {
    category: 'Cost'
    amount: budgetAmount
    timeGrain: 'Monthly'
    timePeriod: {
      startDate: budgetStartDate
    }
    notifications: {
      forecast80: {
        enabled: true
        operator: 'GreaterThan'
        threshold: 80
        thresholdType: 'Forecasted'
        contactEmails: [ budgetContactEmail ]
      }
      actual100: {
        enabled: true
        operator: 'GreaterThan'
        threshold: 100
        thresholdType: 'Actual'
        contactEmails: [ budgetContactEmail ]
      }
    }
  }
}

// =====================================================================
//  Container Registry
// =====================================================================
resource acr 'Microsoft.ContainerRegistry/registries@2023-07-01' = {
  name: acrName
  location: location
  tags: tags
  sku: { name: 'Basic' }
  properties: {
    adminUserEnabled: false
  }
}

resource acrPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(acr.id, uami.id, roleAcrPull)
  scope: acr
  properties: {
    principalId: uami.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleAcrPull)
  }
}

// =====================================================================
//  Key Vault (RBAC)
// =====================================================================
resource kv 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: kvName
  location: location
  tags: tags
  properties: {
    sku: { family: 'A', name: 'standard' }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
    enableSoftDelete: true
  }
}

resource kvSecretsUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(kv.id, uami.id, roleKvSecretsUser)
  scope: kv
  properties: {
    principalId: uami.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleKvSecretsUser)
  }
}

// =====================================================================
//  Virtual network (private networking for Cosmos DB)
// =====================================================================
resource vnet 'Microsoft.Network/virtualNetworks@2023-11-01' = {
  name: vnetName
  location: location
  tags: tags
  properties: {
    addressSpace: { addressPrefixes: [ '10.20.0.0/22' ] }
    subnets: [
      {
        name: 'aca'
        properties: {
          addressPrefix: '10.20.0.0/27'
          delegations: [
            { name: 'aca', properties: { serviceName: 'Microsoft.App/environments' } }
          ]
        }
      }
      {
        name: 'pe'
        properties: {
          addressPrefix: '10.20.1.0/24'
          privateEndpointNetworkPolicies: 'Disabled'
        }
      }
    ]
  }
}

// =====================================================================
//  Cosmos DB (NoSQL, serverless) — PRIVATE (no public access)
// =====================================================================
resource cosmos 'Microsoft.DocumentDB/databaseAccounts@2024-11-15' = {
  name: cosmosName
  location: location
  tags: tags
  kind: 'GlobalDocumentDB'
  properties: {
    databaseAccountOfferType: 'Standard'
    enableFreeTier: false
    capabilities: [ { name: 'EnableServerless' } ]
    consistencyPolicy: { defaultConsistencyLevel: 'Session' }
    disableLocalAuth: true
    publicNetworkAccess: 'Disabled'
    locations: [ { locationName: location, failoverPriority: 0, isZoneRedundant: false } ]
  }
}

resource cosmosDb 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases@2024-11-15' = {
  parent: cosmos
  name: cosmosDatabase
  properties: {
    resource: { id: cosmosDatabase }
  }
}

var containers = [
  { name: 'brands', pk: '/id', ttl: null }
  { name: 'agents', pk: '/id', ttl: null }
  { name: 'industries', pk: '/name', ttl: null }
  { name: 'users', pk: '/email', ttl: null }
  { name: 'audit', pk: '/id', ttl: null }
  { name: 'savedViews', pk: '/userId', ttl: null }
  { name: 'outreach', pk: '/id', ttl: null }
  { name: 'conversations', pk: '/userId', ttl: null }
  { name: 'documents', pk: '/userId', ttl: null }
  { name: 'crm', pk: '/companyId', ttl: null }
  { name: 'profiles', pk: '/id', ttl: null }
  // Login codes and reset tokens. Partitioned by email because every read is
  // "the challenges for this address". defaultTtl -1 turns TTL ON with no
  // default: without it Cosmos IGNORES the per-item ttl the app writes, and
  // spent codes would pile up forever.
  { name: 'authChallenges', pk: '/email', ttl: -1 }
]

resource cosmosContainers 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = [
  for c in containers: {
    parent: cosmosDb
    name: c.name
    properties: {
      // defaultTtl is OMITTED rather than set to null when a container has no
      // TTL: Cosmos rejects an explicit null with "One of the specified inputs
      // is invalid", which ARM validation does not catch because it never
      // reaches the data plane.
      resource: union(
        {
          id: c.name
          partitionKey: { paths: [ c.pk ], kind: 'Hash' }
        },
        c.ttl == null ? {} : { defaultTtl: c.ttl }
      )
    }
  }
]

// data-plane access for the app identity
resource cosmosDataRole 'Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments@2024-11-15' = {
  parent: cosmos
  name: guid(cosmos.id, uami.id, roleCosmosDataContributor)
  properties: {
    principalId: uami.properties.principalId
    roleDefinitionId: '${cosmos.id}/sqlRoleDefinitions/${roleCosmosDataContributor}'
    scope: cosmos.id
  }
}

// private endpoint + private DNS for Cosmos (reachable only from the VNet)
resource cosmosPe 'Microsoft.Network/privateEndpoints@2023-11-01' = {
  name: cosmosPeName
  location: location
  tags: tags
  properties: {
    subnet: { id: '${vnet.id}/subnets/pe' }
    privateLinkServiceConnections: [
      {
        name: 'cosmos'
        properties: {
          privateLinkServiceId: cosmos.id
          groupIds: [ 'Sql' ]
        }
      }
    ]
  }
}

resource cosmosDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' = {
  name: 'privatelink.documents.azure.com'
  location: 'global'
  tags: tags
}

resource cosmosDnsLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = {
  parent: cosmosDnsZone
  name: '${vnetName}-link'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: { id: vnet.id }
  }
}

resource cosmosPeDns 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-11-01' = {
  parent: cosmosPe
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      { name: 'documents', properties: { privateDnsZoneId: cosmosDnsZone.id } }
    ]
  }
}

// =====================================================================
//  Azure AI Foundry — NEW Foundry (V2): account + project + model
//  Grounded in MS Learn:
//   - Bicep sample: https://learn.microsoft.com/azure/templates/microsoft.cognitiveservices/accounts/projects
//   - Create a project: https://learn.microsoft.com/azure/foundry/how-to/create-projects
//  `allowProjectManagement: true` is what makes this a new Foundry account
//  (enables `projects` child resources). This is basic agent setup — agent
//  thread state lives in Microsoft-managed storage, so our serverless app
//  Cosmos DB stays independent. (Standard setup w/ capabilityHosts needs
//  provisioned-throughput Cosmos: 3-5 containers @ >=1000 RU/s per project.)
// =====================================================================
resource ai 'Microsoft.CognitiveServices/accounts@2025-06-01' = {
  name: aiName
  location: aiLocation
  tags: tags
  kind: 'AIServices'
  sku: { name: 'S0' }
  identity: { type: 'SystemAssigned' }
  properties: {
    allowProjectManagement: true
    customSubDomainName: aiName
    publicNetworkAccess: 'Enabled'
    disableLocalAuth: true
  }
}

// Foundry project (new Foundry child resource) — container for agents/access/data isolation
resource aiProject 'Microsoft.CognitiveServices/accounts/projects@2025-06-01' = {
  parent: ai
  name: aiProjectName
  location: aiLocation
  identity: { type: 'SystemAssigned' }
  properties: {
    displayName: 'data-driven'
    description: 'Business-development copilot: chat-with-your-data and reasoning over the pipeline.'
  }
}

// gpt-5.4-mini model deployment on the Foundry account
resource chatDeployment 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = {
  parent: ai
  name: chatModelName
  sku: { name: 'GlobalStandard', capacity: chatModelCapacity }
  properties: {
    model: { format: 'OpenAI', name: chatModelName, version: chatModelVersion }
  }
}

// text-embedding-3-large — vectorizer for Foundry IQ agentic retrieval (and future memory)
resource embedDeployment 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = {
  parent: ai
  name: embedModelName
  dependsOn: [ chatDeployment ]
  sku: { name: 'Standard', capacity: 50 }
  properties: {
    model: { format: 'OpenAI', name: embedModelName, version: embedModelVersion }
  }
}

// =====================================================================
//  Foundry IQ — Azure AI Search (agentic retrieval), keyless + linked.
//  Basic tier (semantic ranker on the free plan), keyless (Entra-only).
//  Public network access is ENABLED so the Foundry portal and the keyless
//  post-provision hook can manage knowledge sources / knowledge bases; a
//  private endpoint is ALSO kept for the in-VNet data path. Local (key)
//  auth stays disabled, so reachability is Entra-only. A "web" knowledge
//  source (Grounding with Bing) is created at the data plane; Azure AI
//  Search handles the Bing egress + LLM summarization internally.
// =====================================================================
resource search 'Microsoft.Search/searchServices@2024-06-01-preview' = {
  name: searchName
  location: location
  tags: tags
  sku: { name: 'basic' }
  identity: { type: 'SystemAssigned' }
  properties: {
    replicaCount: 1
    partitionCount: 1
    hostingMode: 'default'
    semanticSearch: 'free'
    disableLocalAuth: true
    publicNetworkAccess: 'enabled'
  }
}

// search -> call the embedding deployment (keyless vectorizer)
resource searchToAi 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(ai.id, search.id, roleOpenAIUser)
  scope: ai
  properties: {
    principalId: search.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleOpenAIUser)
  }
}

// Foundry project -> read search indexes for agentic retrieval (keyless, ProjectManagedIdentity)
resource projectToSearch 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(search.id, aiProject.id, roleSearchIndexReader)
  scope: search
  properties: {
    principalId: aiProject.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleSearchIndexReader)
  }
}

// search -> read the AI account & call the chat model for knowledge-base query
// planning, answer synthesis, and web-content summarization (keyless). The
// knowledge base's model reference authenticates with the search identity.
resource searchToAiCogSvc 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(ai.id, search.id, roleCogSvcUser)
  scope: ai
  properties: {
    principalId: search.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleCogSvcUser)
  }
}

// Foundry project -> manage knowledge sources / bases on the search service so
// they are manageable from the Foundry portal (keyless, project identity).
resource projectSearchContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(search.id, aiProject.id, roleSearchServiceContributor)
  scope: search
  properties: {
    principalId: aiProject.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleSearchServiceContributor)
  }
}

// deployer -> create/manage knowledge sources + knowledge bases from the keyless
// post-provision hook (and directly in the Azure/Foundry portal).
resource deployerSearchContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(deployerPrincipalId)) {
  name: guid(search.id, deployerPrincipalId, roleSearchServiceContributor)
  scope: search
  properties: {
    principalId: deployerPrincipalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleSearchServiceContributor)
  }
}

// deployer/admin -> query knowledge bases (retrieve) to verify + test in the portal.
resource deployerSearchReader 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(deployerPrincipalId)) {
  name: guid(search.id, deployerPrincipalId, roleSearchIndexReader)
  scope: search
  properties: {
    principalId: deployerPrincipalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleSearchIndexReader)
  }
}

// app identity -> query the web knowledge base (agentic retrieve) at runtime, keyless.
resource uamiSearchReader 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(search.id, uami.id, roleSearchIndexReader)
  scope: search
  properties: {
    principalId: uami.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleSearchIndexReader)
  }
}

// Link the search service INTO the Foundry project as a CognitiveSearch
// connection (keyless / project identity) so its knowledge sources and
// knowledge bases are managed from the Foundry portal.
resource searchConnection 'Microsoft.CognitiveServices/accounts/projects/connections@2025-06-01' = {
  parent: aiProject
  name: searchName
  properties: {
    category: 'CognitiveSearch'
    target: 'https://${searchName}.search.windows.net'
    authType: 'AAD'
    metadata: {
      ApiType: 'Azure'
      ResourceId: search.id
      location: search.location
    }
  }
}

// private endpoint + DNS for Search (in-VNet data path; public stays enabled)
resource searchPe 'Microsoft.Network/privateEndpoints@2023-11-01' = {
  name: searchPeName
  location: location
  tags: tags
  properties: {
    subnet: { id: '${vnet.id}/subnets/pe' }
    privateLinkServiceConnections: [
      { name: 'search', properties: { privateLinkServiceId: search.id, groupIds: [ 'searchService' ] } }
    ]
  }
}

resource searchDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' = {
  name: 'privatelink.search.windows.net'
  location: 'global'
  tags: tags
}

resource searchDnsLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = {
  parent: searchDnsZone
  name: '${vnetName}-search-link'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: { id: vnet.id }
  }
}

resource searchPeDns 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-11-01' = {
  parent: searchPe
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [ { name: 'search', properties: { privateDnsZoneId: searchDnsZone.id } } ]
  }
}

// app identity -> inference. Documented role: "Web app -> Azure OpenAI -> Inference".
resource openAiUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(ai.id, uami.id, roleOpenAIUser)
  scope: ai
  properties: {
    principalId: uami.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleOpenAIUser)
  }
}

// app identity -> read the AI Services account & resolve model deployments
resource cogSvcUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(ai.id, uami.id, roleCogSvcUser)
  scope: ai
  properties: {
    principalId: uami.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleCogSvcUser)
  }
}

// app identity -> keyless speech-to-text + text-to-speech (Luca voice)
resource speechUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(ai.id, uami.id, roleSpeechUser)
  scope: ai
  properties: {
    principalId: uami.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleSpeechUser)
  }
}

// app identity -> create/edit + consume Foundry agents (data plane)
resource foundryUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(ai.id, uami.id, roleFoundryUser)
  scope: ai
  properties: {
    principalId: uami.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleFoundryUser)
  }
}

// -------------------------------------------------------------------
//  Foundry PROMPT AGENT (data-plane, keyless)
//  Prompt agents are created via the Foundry Projects API, not ARM. A Bicep
//  `deploymentScripts` would require storage-account KEYS, which the no-key
//  policy forbids — so the agent is created by the keyless azd `postprovision`
//  hook (scripts/create-agent.sh) with the deployer's Entra token. The deployer
//  is granted Foundry Project Manager here so it can create the agent.
//  Docs: https://learn.microsoft.com/azure/foundry/agents/quickstarts/prompt-agent
// -------------------------------------------------------------------
resource deployerAgentCreator 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(deployerPrincipalId)) {
  name: guid(ai.id, deployerPrincipalId, roleFoundryProjectManager)
  scope: ai
  properties: {
    principalId: deployerPrincipalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleFoundryProjectManager)
  }
}

// =====================================================================
//  Communication Services (optional — one-click email outreach)
// =====================================================================
// The bare communicationServices resource cannot send anything: it needs an
// email service, a domain, and the domain linked back to it. Provisioning only
// the first of those billed for a resource that silently never delivered.
resource emailService 'Microsoft.Communication/emailServices@2023-04-01' = if (deployEmail) {
  name: emailServiceName
  location: 'global'
  tags: tags
  properties: {
    dataLocation: 'Europe'
  }
}

// Azure-managed domain: no DNS to verify, so it survives a hands-off deploy.
// The name is fixed by the platform — it must be exactly 'AzureManagedDomain'.
resource emailDomain 'Microsoft.Communication/emailServices/domains@2023-04-01' = if (deployEmail) {
  parent: emailService
  name: 'AzureManagedDomain'
  location: 'global'
  tags: tags
  properties: {
    domainManagement: 'AzureManaged'
    userEngagementTracking: 'Disabled'
  }
}

resource acs 'Microsoft.Communication/communicationServices@2023-04-01' = if (deployEmail) {
  name: acsName
  location: 'global'
  tags: tags
  properties: {
    dataLocation: 'Europe'
    linkedDomains: [ emailDomain.id ]
  }
}

// The app sends with DefaultAzureCredential, so the identity needs a data-plane
// role on the ACS resource — otherwise every send fails 401 at runtime.
resource acsRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (deployEmail) {
  scope: acs
  name: guid(acs.id, uami.id, roleCommunicationEmailOwner)
  properties: {
    principalId: uami.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleCommunicationEmailOwner)
  }
}

// =====================================================================
//  Container Apps
// =====================================================================
resource cae 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: caeName
  location: location
  tags: tags
  properties: {
    // Keyless logging: route to Azure Monitor, then a diagnostic setting to Log Analytics.
    appLogsConfiguration: {
      destination: 'azure-monitor'
    }
    // VNet-integrated so the app can reach the private Cosmos endpoint.
    vnetConfiguration: {
      infrastructureSubnetId: '${vnet.id}/subnets/aca'
      internal: false
    }
    workloadProfiles: [
      { name: 'Consumption', workloadProfileType: 'Consumption' }
    ]
  }
}

// Container Apps env logs -> Log Analytics via diagnostic settings (Entra, no shared key)
resource caeDiag 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  scope: cae
  name: 'to-law'
  properties: {
    workspaceId: logs.id
    logs: [ { categoryGroup: 'allLogs', enabled: true } ]
  }
}

// Email settings only exist when the email stack was deployed. The sender uses
// safe dereference: a reference to a resource whose condition is false fails
// validation outright, so the ternary alone is not enough (BCP318).
var emailEnv = deployEmail
  ? [
      { name: 'ACS_ENDPOINT', value: 'https://${acsName}.communication.azure.com' }
      { name: 'ACS_SENDER_ADDRESS', value: 'DoNotReply@${emailDomain.?properties.?fromSenderDomain}' }
    ]
  : []

var reasoningEnv = [ { name: 'COPILOT_REASONING_EFFORT', value: reasoningEffort } ]

// Off unless a custom mail domain is attached. An Azure Managed Domain allows
// 10 sends an hour for the whole subscription, and sign-in is the highest
// frequency mail there is: leaving this on would starve password reset and
// outreach of the same quota.
var otpEnv = [ { name: 'OTP_LOGIN_ENABLED', value: enableOtpLogin ? 'true' : 'false' } ]

var baseEnv = [
  { name: 'PORT', value: '3000' }
  { name: 'AZURE_CLIENT_ID', value: uami.properties.clientId }
  { name: 'AUTH_SECRET', secretRef: 'auth-secret' }
  { name: 'AUTH_TRUST_HOST', value: 'true' }
  // The app's own public origin, used as the server URL in the OpenAPI document
  // the Foundry agent reads. Composed from the environment's domain rather than
  // the app's own fqdn, which would be a self-reference.
  { name: 'APP_URL', value: 'https://${appName}.${cae.properties.defaultDomain}' }
  { name: 'COSMOS_ENDPOINT', value: cosmos.properties.documentEndpoint }
  { name: 'COSMOS_DATABASE', value: cosmosDatabase }
  { name: 'AZURE_OPENAI_ENDPOINT', value: ai.properties.endpoint }
  { name: 'AZURE_OPENAI_DEPLOYMENT', value: chatModelName }
  { name: 'COPILOT_CHAT_ENDPOINT', value: 'https://${aiName}.services.ai.azure.com/openai/v1/chat/completions?api-version=preview' }
  { name: 'AZURE_AI_OPENAI_V1', value: 'https://${aiName}.services.ai.azure.com/openai/v1' }
  { name: 'COPILOT_MODEL', value: chatModelName }
  { name: 'SPEECH_VOICE', value: speechVoice }
  { name: 'SPEECH_LANG', value: speechLang }
  { name: 'AZURE_AI_PROJECT_ENDPOINT', value: 'https://${aiName}.services.ai.azure.com/api/projects/${aiProjectName}' }
  { name: 'AZURE_AI_PROJECT_NAME', value: aiProjectName }
  { name: 'AZURE_AI_AGENT_NAME', value: agentName }
  { name: 'AZURE_SEARCH_ENDPOINT', value: 'https://${searchName}.search.windows.net' }
  // Injected rather than left to the app's default, so renaming the knowledge
  // source here cannot silently break web search at runtime.
  { name: 'AZURE_SEARCH_WEB_KS', value: searchWebKsName }
  { name: 'AZURE_SEARCH_KNOWLEDGE_BASE', value: searchKbName }
  { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: appInsights.properties.ConnectionString }
]

resource app 'Microsoft.App/containerApps@2024-03-01' = {
  name: appName
  location: location
  // azd matches services to this tag
  tags: union(tags, { 'azd-service-name': 'web' })
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${uami.id}': {} }
  }
  properties: {
    managedEnvironmentId: cae.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 3000
        transport: 'auto'
      }
      registries: [
        { server: acr.properties.loginServer, identity: uami.id }
      ]
      secrets: [
        { name: 'auth-secret', value: authSecret }
      ]
    }
    template: {
      containers: [
        {
          name: 'web'
          image: webImage
          resources: { cpu: json('0.5'), memory: '1Gi' }
          env: concat(baseEnv, emailEnv, reasoningEnv, otpEnv)
        }
      ]
      // minReplicas: 1 keeps one instance always warm (no cold starts). Cost of
      // one always-on Consumption replica is accepted (user directive 2026-07-12).
      scale: { minReplicas: 1, maxReplicas: 3 }
    }
  }
}

// =====================================================================
//  Outputs (consumed by azd / the app)
// =====================================================================
output AZURE_CONTAINER_REGISTRY_ENDPOINT string = acr.properties.loginServer
output AZURE_CONTAINER_REGISTRY_NAME string = acr.name
output WEB_URI string = 'https://${app.properties.configuration.ingress.fqdn}'
output COSMOS_ENDPOINT string = cosmos.properties.documentEndpoint
output COSMOS_DATABASE string = cosmosDatabase
output AZURE_OPENAI_ENDPOINT string = ai.properties.endpoint
output AZURE_OPENAI_DEPLOYMENT string = chatModelName
output AZURE_AI_FOUNDRY_NAME string = ai.name
output AZURE_AI_PROJECT_NAME string = aiProject.name
output AZURE_AI_PROJECT_ENDPOINT string = 'https://${aiName}.services.ai.azure.com/api/projects/${aiProjectName}'
output AZURE_AI_AGENT_NAME string = agentName
output AGENT_INSTRUCTIONS string = agentInstructions
output KEY_VAULT_NAME string = kv.name
output MANAGED_IDENTITY_CLIENT_ID string = uami.properties.clientId
output AZURE_SEARCH_ENDPOINT string = 'https://${searchName}.search.windows.net'
output AZURE_SEARCH_NAME string = search.name
output AZURE_EMBEDDING_DEPLOYMENT string = embedModelName
output AZURE_SEARCH_CONNECTION_NAME string = searchConnection.name
output AZURE_SEARCH_WEB_KS string = searchWebKsName
output AZURE_SEARCH_KNOWLEDGE_BASE string = searchKbName
output APP_INSIGHTS_WORKBOOK_ID string = workbook.id
