// Interactive product tour — an end-to-end guided walkthrough of every surface
// in the app, cross-referenced to the source "Business Development – Client
// Segmentation" workbook (6 tabs: Brands Operative, Brand Data, Brand Analysis,
// Sales Strategy, AgentsAgencies, Agency Data).
//
// Each step optionally spotlights a `[data-tour="…"]` anchor on a given route.
// Steps with no `selector` render a centered card. `optional` steps are skipped
// silently when their anchor is absent (e.g. admin-only controls for members).

export type TourPlacement = "top" | "bottom" | "left" | "right" | "center";

/** One label, so the badge and the copy that refers to it cannot disagree. */
export const TOUR_NEW_BADGE = "New in v1.2";

export interface TourStep {
  id: string;
  route: string;
  selector?: string;
  title: string;
  body: string;
  /** How this maps back to the source sheet. */
  sheet?: string;
  /** Badged as new so returning users can see what changed. */
  isNew?: boolean;
  placement?: TourPlacement;
  optional?: boolean;
}

export const TOUR_STEPS: TourStep[] = [
  {
    id: "welcome",
    route: "/dashboard",
    title: "Welcome to BD Intelligence",
    body: `This is your Client Segmentation sheet, turned into a live, scored, searchable workspace. Let's walk through everything — it takes about a minute. Steps badged “${TOUR_NEW_BADGE}” are what changed since you last looked.`,
    sheet: "Everything here is built from the 6 tabs of the workbook.",
    placement: "center",
  },
  {
    id: "nav",
    route: "/dashboard",
    selector: '[data-tour="nav"]',
    title: "Your command bar",
    body: "Jump between Overview, Pipeline, Scoring, Industries, Whitespace, Data Quality and the Copilot. The active section stays lit.",
    placement: "bottom",
  },
  {
    id: "command",
    route: "/dashboard",
    selector: '[data-tour="command"]',
    title: "Jump anywhere — ⌘K",
    body: "Press ⌘K (Ctrl-K on Windows/Linux) any time to open the command palette: search a lead by name, jump to any section, or run a quick action like asking the Copilot or replaying this tour.",
    placement: "bottom",
    optional: true,
  },
  {
    id: "overview-kpis",
    route: "/dashboard",
    selector: '[data-tour="kpis"]',
    title: "Headline metrics",
    body: "Four numbers at a glance: how many leads you hold, the probability-weighted value of the live ones, deals closed, and how much of the pipeline is scored. Weighted value counts OPEN deals only — a won deal has a 100% chance of closing, so including it would add money already banked to a figure about what might still come in.",
    sheet: "Rolled up from Brands Operative (status) + Brand Data (scores).",
    placement: "bottom",
  },
  {
    id: "overview-funnel",
    route: "/dashboard",
    selector: '[data-tour="funnel"]',
    title: "Pipeline by stage",
    body: "See how leads are distributed across the sales funnel, from first contact to closed.",
    sheet: "Mirrors the Status column in Brands Operative (Deal Closed, Advanced, Follow Up, Early, Back to Attack, Recurring, Still to open, Did not work out).",
    placement: "right",
  },
  {
    id: "overview-quadrant",
    route: "/dashboard",
    selector: '[data-tour="quadrant"]',
    title: "Priority quadrant",
    body: "Every scored lead plotted by opportunity (Y) against winnability (X); bubble size is the deal value. Hover any bubble for its name. Top-right = go after it now.",
    sheet: "Straight from the Brand Data scoring model.",
    placement: "left",
  },
  {
    id: "overview-heatmap",
    route: "/dashboard",
    selector: '[data-tour="heatmap"]',
    title: "Industry scorecard",
    body: "A segment-level view of how attractive each industry is, recomputed from the underlying data.",
    sheet: "Derived from the Brand Analysis tab.",
    placement: "top",
  },
  {
    id: "pipeline",
    route: "/dashboard/pipeline",
    selector: '[data-tour="nav"]',
    title: "Pipeline — the lead tracker",
    body: "The heart of the app: your full, editable lead list. This is the Brands Operative tab, live.",
    sheet: "Brands Operative: name, status, priority, owner, POC, industry, contact dates, follow-up, notes.",
    placement: "bottom",
  },
  {
    id: "pipe-search",
    route: "/dashboard/pipeline",
    selector: '[data-tour="pipe-search"]',
    title: "Search & filter",
    body: "Find anything fast — search by brand, POC or notes, then narrow by status and owner.",
    placement: "bottom",
  },
  {
    id: "pipe-newlead",
    route: "/dashboard/pipeline",
    selector: '[data-tour="pipe-newlead"]',
    title: "Add a lead",
    body: "Create a new lead here. The editor captures every field from the sheet — status, priority, owner, POC, industry, commercial value, the four 0–5 scores, contact dates and notes.",
    sheet: "One row of Brands Operative = one lead.",
    placement: "bottom",
  },
  {
    id: "pipe-export",
    route: "/dashboard/pipeline",
    selector: '[data-tour="pipe-export"]',
    title: "Export the view",
    body: "Download exactly what you're looking at (respecting filters) as CSV, JSON, Excel (.xlsx) or PDF — handy for sharing, reporting or reconciling with the sheet.",
    placement: "bottom",
  },
  {
    id: "pipe-views",
    route: "/dashboard/pipeline",
    selector: '[data-tour="pipe-views"]',
    title: "Saved views",
    body: "Save a search + filter + sort combination as a named view (e.g. \"My hot leads\") and jump back to it in one click.",
    placement: "bottom",
  },
  {
    id: "pipe-lifecycle",
    route: "/dashboard/pipeline",
    selector: '[data-tour="pipe-lifecycle"]',
    title: "Only what is still live",
    body: "The list opens on Active, so finished deals stop crowding a view about what to do next — but they are one chip away, not gone: Won, Lost and Everything sit right here with their counts. Search still reaches them; if you look for a client who happens to be won, the table says so and offers to show it rather than coming up empty.",
    isNew: true,
    placement: "bottom",
  },
  {
    id: "pipe-health",
    route: "/dashboard/pipeline",
    selector: '[data-tour="pipe-health"]',
    title: "What the book is worth, and who owes the next move",
    body: "Five headlines answer what the sheet never could: the total value of the live pipeline, the value of proposals sent and still unanswered, how many leads are late because WE owe a reply, how many because they owe US a decision, and how many nobody has triaged at all. Each count is also a filter — click it and the table drops to just those leads. The Waiting-on column shows the side and how many days overdue.",
    sheet: "Inferred where you have not said: a proposal out for decision means the ball is with them; a lone follow-up date means it is with us. An inferred side is marked with a “?” you can hover for the reason, so “Us, 142 days late” never looks like something a person decided when it was not. Neither signal, and the lead is reported as untriaged rather than quietly filed under one side.",
    isNew: true,
    placement: "bottom",
  },
  {
    id: "pipe-edit",
    route: "/dashboard/pipeline",
    selector: '[data-tour="pipe-edit"]',
    title: "Edit & open a lead",
    body: "Edit any row inline, or click a brand name to open its detail page with the full scoring breakdown and activity.",
    placement: "left",
    optional: true,
  },
  {
    id: "lead-detail",
    route: "/dashboard/pipeline",
    selector: '[data-tour="pipe-edit"]',
    title: "What a lead page now holds",
    body: "Everything about a lead in one place: who owes the next move and by when, how long the deal is actually taking versus what you expected, its proposals and their status, and its commercial value — labelled with where that figure came from, because an accepted offer, an ask still sitting with the client and a number somebody typed at the start are three different kinds of true. Accepting a proposal writes the real number in and keeps the original estimate, so you can see how good the guess was. Plus a strategic value, which is how a cheap or free project can still rank: a logo you can name, a referral source, a reference case.",
    sheet: "The edit dialog holds the rest — status, priority, owner, contacts, dates, commercial value and the four 0–5 judgements behind the score. Deleting lives at the bottom of it, behind a confirm. It is permanent and needs the delete permission.",
    isNew: true,
    placement: "left",
    optional: true,
  },
  {
    id: "scoring",
    route: "/dashboard/scoring",
    selector: '[data-tour="nav"]',
    title: "Scoring model",
    body: "Rebuilt. Every lead now sits on two axes: Opportunity (what it is worth, discounted by how sure we are of the budget, plus its strategic value) and Winnability (how likely we are to land it). They are combined with a geometric mean, so a lead has to be decent on BOTH — a huge deal we will never win no longer outranks a winnable one. You get a 0–100 priority, an A–D grade and a quadrant: Pursue, Invest, Quick win or Park.",
    sheet: "Brand Data, re-weighted. Ease of delivery is still reported — but it is no longer blended in, because being easy is not a reason to want a deal.",
    isNew: true,
    placement: "bottom",
  },
  {
    id: "scoring-reference",
    route: "/dashboard/scoring",
    selector: '[data-tour="scoring-reference"]',
    title: "The model, written out in full",
    body: "Every term, every weight, both quadrant thresholds, the grade bands — and an explicit list of what has NO effect on the ranking. Expected duration is on that list: changing it will never move a bubble, because how long a deal takes is a cost of running it, not a reason to want it or a reason it closes. It also answers when the score recalculates: on every read, nothing cached, and recency decays on its own so an untouched lead drifts down without anybody editing it. The whole page renders from the same constants the ranking uses, so it cannot drift from the code.",
    isNew: true,
    placement: "top",
  },
  {
    id: "companies",
    route: "/dashboard/companies",
    selector: '[data-tour="nav"]',
    title: "Companies — the relationship, not the deal",
    body: "New. A client is no longer one row. Fastweb can have three deals across two years and you see them together: every deal ever run, what the relationship has earned in total, and how much of that was repeat business after the first win. Search it, start the next deal straight from the client, and fold two records into one with Merge. The possible-duplicates card stays deliberately over-inclusive, because missing a real duplicate costs more than dismissing a wrong guess — it suggests, you decide.",
    sheet: "Projected from Brands Operative on every read, so a company can never fall out of step with an edit to one of its deals.",
    isNew: true,
    placement: "bottom",
  },
  {
    id: "industries",
    route: "/dashboard/industries",
    selector: '[data-tour="nav"]',
    title: "Industries & playbook",
    body: "Segment analysis plus the go-to-market playbook: what each industry needs and how to pitch it.",
    sheet: "Brand Analysis (segment metrics) + Sales Strategy (marketing & product needs per industry type).",
    placement: "bottom",
  },
  {
    id: "whitespace",
    route: "/dashboard/whitespace",
    selector: '[data-tour="nav"]',
    title: "Whitespace & TAM",
    body: "Where the untapped opportunity is: market penetration vs. total addressable market, so you know where to expand.",
    sheet: "Modelled from industry sizing in the workbook.",
    placement: "bottom",
  },
  {
    id: "quality",
    route: "/dashboard/quality",
    selector: '[data-tour="nav"]',
    title: "Data quality",
    body: "Keeps the pipeline clean — flags missing fields, unscored leads and stale contacts so nothing slips through. Rows whose imported outcome contradicts their stage get their own review card, and you can close one by confirming the stage is the right answer. That figure came from the original spreadsheet's outcome column and had no control anywhere, so a lead you correctly marked “Did not work out” used to stay flagged forever.",
    sheet: "Continuous checks against the Brands Operative / Brand Data structure.",
    isNew: true,
    placement: "bottom",
  },
  {
    id: "copilot",
    route: "/dashboard/copilot",
    selector: '[data-tour="nav"]',
    title: "Meet the Copilot",
    body: "Chat with your pipeline in plain language. It answers with live charts, tables and cards — grounded in your real data, acting as you.",
    placement: "bottom",
  },
  {
    id: "copilot-suggestions",
    route: "/dashboard/copilot",
    selector: '[data-tour="copilot-suggestions"]',
    title: "Ask anything",
    body: "Start with a suggestion or ask your own. The starters changed in v1.1: “What should I do today?”, “What's at risk of going cold?” and “What am I allowed to do?” now sit alongside “Summarise the pipeline”.",
    isNew: true,
    placement: "right",
    optional: true,
  },
  {
    id: "copilot-workqueue",
    route: "/dashboard/copilot",
    selector: '[data-tour="copilot-suggestions"]',
    title: "“What should I do today?”",
    body: "New, and the one to try first. It returns a single ranked list of every lead that needs a human — follow-ups you have missed, clients nobody has chased, deals nobody has triaged, deals gone quiet — ordered by what is at stake rather than by date, so a large deal two days late outranks a small one two weeks late. Each lead appears once, under its worst reason, and each row carries the action that clears it.",
    isNew: true,
    placement: "right",
    optional: true,
  },
  {
    id: "copilot-reasoning",
    route: "/dashboard/copilot",
    selector: '[data-tour="copilot-reasoning"]',
    title: "Deep reasoning",
    body: "Toggle “Think deeply” for tougher questions — the Copilot spends more reasoning effort on the answer and shows its step-by-step thinking. In v1.1 this switch actually does something: it raises the effort sent with the request rather than pretending to swap models.",
    isNew: true,
    placement: "top",
  },
  {
    id: "copilot-attach",
    route: "/dashboard/copilot",
    selector: '[data-tour="copilot-attach"]',
    title: "Chat with your documents",
    body: "Attach a PDF, Word doc, deck or spreadsheet and ask about it — the Copilot reads it and answers with citations. Perfect for briefs, proposals and research.",
    placement: "top",
    optional: true,
  },
  {
    id: "copilot-mic",
    route: "/dashboard/copilot",
    selector: '[data-tour="copilot-mic"]',
    title: "Ask out loud",
    body: "Tap the mic to speak your question instead of typing — it's transcribed and sent like any other message, and answers can be read back aloud with “Listen”.",
    placement: "top",
    optional: true,
  },
  {
    id: "copilot-input",
    route: "/dashboard/copilot",
    selector: '[data-tour="copilot-input"]',
    title: "It can act, too — 42 tools now",
    body: "It went from 14 tools to 42, and the gap it closed was everything the screens could do and the chat could not. It can add a lead, edit its fields, set its commercial value, move it through the stages, record or remove a proposal, merge two companies, link or unlink a deal, complete or snooze a follow-up, set strategic value, reassign an owner, cancel a draft, send outreach and delete a lead — as well as report data quality, deal pace, budget accuracy, the audit trail for one lead, dormant clients worth revisiting and the money going cold. Ask it how anything works and it reads the scoring model and the product manual back to you out of the code itself — every weight, every route, every instruction, and its own capability list.",
    sheet: "Every tool runs as you and checks the same permission the screens check, so the chat is never a way round the rules — if you cannot delete a lead on screen, asking nicely will not do it either. Writes are logged as yours “via copilot”, and anything irreversible — deleting, merging, sending — arrives as a button you press, never fired off because a sentence sounded like a request.",
    isNew: true,
    placement: "top",
  },
  {
    id: "reminders",
    route: "/dashboard",
    selector: '[data-tour="topbar-reminders"]',
    title: "Follow-up reminders",
    body: "Never miss a touch. The bell counts what's due today; this inbox lists everything with snooze and done.",
    sheet: "Driven by the Follow Up date column in Brands Operative.",
    placement: "left",
    optional: true,
  },
  {
    id: "outbox",
    route: "/dashboard",
    selector: '[data-tour="topbar-outbox"]',
    title: "Outreach outbox",
    body: "Drafted emails collect here. Members draft; admins review, approve and send — so nothing goes out unchecked.",
    placement: "left",
    optional: true,
  },
  {
    id: "activity",
    route: "/dashboard",
    selector: '[data-tour="topbar-activity"]',
    title: "Activity — audit trail",
    body: "Every change to the pipeline is logged here: who did what, when. (Admins only.)",
    placement: "left",
    optional: true,
  },
  {
    id: "team",
    route: "/dashboard",
    selector: '[data-tour="topbar-team"]',
    title: "Access — far past admin vs member",
    body: "Rebuilt. There are now 44 separate permissions across ten areas, and most are scoped: none, only your own records, your team's, or everything. So “see every lead but only edit mine” is a real, expressible answer. They are bundled into profiles — Administrator, Sales manager, Sales rep, Operations & analysis, Read only — which you assign per person, with individual grants or denials on top. A denial always wins. Ask the Copilot “What am I allowed to do?” and it will tell you exactly.",
    isNew: true,
    placement: "left",
    optional: true,
  },
  {
    id: "recovery",
    route: "/dashboard",
    title: "Locked out? Not any more",
    body: "New. Passwords are stored as one-way hashes, so a forgotten one was genuinely unrecoverable — there was no reset at all, not even for an admin. “Forgot password?” on the sign-in page now emails a single-use link that expires in 30 minutes. Asking for one tells nobody anything: a registered address and an unknown one get exactly the same reply, so the form cannot be used to discover who has an account.",
    sheet: "Signing in with a six-digit emailed code also exists, but ships switched off: a managed mail domain allows only 10 sends an hour across the whole subscription, so it needs a custom domain before it is turned on.",
    isNew: true,
    placement: "center",
  },
  {
    id: "finish",
    route: "/dashboard",
    title: "You're all set",
    body: "That's the whole app. v1.1 added the two-axis scoring model, pipeline health, Companies, granular permissions and a Copilot that can do 31 things instead of 14. Replay this tour anytime from the “?” button in the top bar. Now go close some deals.",
    placement: "center",
  },
];
